version: "2"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - ENV=dev
    volumes:
      - ./:/home/node/app
    command: bash -c "npm install && npm start"
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    restart: always