version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
    command: bash -c "npm install && npm run build && npm run dev"
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    restart: always